version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: university-feedback
    ports:
      - '5433:5432' # 5432 là cổng mặc định của Postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: UniversityFeedback
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
