version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: university-feedback
    ports:
      - '33061:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: UniversityFeedback
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: