name: CI Workflow
description: This workflow runs on pushes and pull requests to the dev branch, checking linting and building the project.
# This workflow is triggered on pushes and pull requests to the dev branch.

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Check lint & Run build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # Install all dependencies for the workspace
      - name: Install dependencies
        run: npm install

      # Lint backend and frontend
      - name: Lint backend
        run: npm run lint --workspace=backend

      - name: Lint frontend
        run: npm run lint --workspace=frontend

      # Build

      - name: Build backend
        run: npm run build --workspace=backend

      - name: Build frontend
        run: npm run build --workspace=frontend
